### PR TITLE
Update to support latest `p2panda-js` version

### PR DESCRIPTION
**Pull request by adzialocha**
Related: https://github.com/p2panda/p2panda/pull/165 and https://github.com/p2panda/p2panda/pull/177

### CODE REVIEW

**Review by sandreae — APPROVED** [review]
Looks good to me! Thx :+1: 

Glad we don't have `message.fields.message` anymore ;-p

**Comment by sandreae** [comment]
and it runs fine for me locally with `update-js-api` p2panda branch.

**Comment by adzialocha** [comment]
Super! I would maybe wait with the merge until we released `p2panda-js@0.3.0`?

**Comment by sandreae** [comment]
Maybe with `p2panda-js@0.3.0` we could even re-design the demo a little to allow for document updates to occur?

**Comment by adzialocha** [comment]
I would merge is anyway now as we probably will not be able to release p2panda v0.3.0 in the next months (too many unpublished crate dependencies like `cddl` and `openmls`).

**Review by cafca — CHANGES_REQUESTED** [review]
`package.json` doesn't install p2panda-js from Github (but uses the published version that isn't compatible with these changes). I tried changing that dependency but somehow couldn't get it to work.

Other than that I am all for merging.

**Comment by adzialocha** [comment]
> ... doesn't install p2panda-js from Github

This would require us to check in the build artefacts into git (aka the `lib` folder).

I suggest we make an npm release now (p2panda `0.3.0`) and then merge this PR?

**Review by cafca — APPROVED** [review]

**Pull request merged**
